structure(list(url = "https://hillcrestgeo.ca/fwa/v1/geojson/whse_basemapping.fwa_stream_networks_sp?filter=gnis_name%20%3D%20%27Sangan%20River%27&bounds=-122.01%2C49.11%2C-121.86%2C49.16&geom_column=geom", 
    status_code = 502L, headers = structure(list(server = "nginx/1.10.3 (Ubuntu)", 
        date = "Wed, 10 Jun 2020 01:36:10 GMT", `content-type` = "text/html", 
        `content-length` = "182", connection = "keep-alive"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 502L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.10.3 (Ubuntu)", 
            date = "Wed, 10 Jun 2020 01:36:10 GMT", `content-type` = "text/html", 
            `content-length` = "182", connection = "keep-alive"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"), 
    date = structure(1591752970, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4e-05, 
    connect = 4.2e-05, pretransfer = 1e-04, starttransfer = 0.380019, 
    total = 0.380046)), class = "response")
