structure(list(url = "https://hillcrestgeo.ca/fwa/v1/geojson/whse_basemapping.fwa_lakes_poly?filter=gnis_name%20%3D%20%27Adams%20Lake%27", 
    status_code = 500L, headers = structure(list(server = "nginx/1.10.3 (Ubuntu)", 
        date = "Wed, 10 Jun 2020 01:40:12 GMT", `content-type` = "application/json; charset=utf-8", 
        `content-length` = "113", connection = "keep-alive", 
        `cache-control` = "private, max-age=3600", `access-control-allow-origin` = "*"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 500L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.10.3 (Ubuntu)", 
            date = "Wed, 10 Jun 2020 01:40:12 GMT", `content-type` = "application/json; charset=utf-8", 
            `content-length` = "113", connection = "keep-alive", 
            `cache-control` = "private, max-age=3600", `access-control-allow-origin` = "*"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"statusCode\":500,\"code\":\"42703\",\"error\":\"Internal Server Error\",\"message\":\"column \\\"gnis_name\\\" does not exist\"}"), 
    date = structure(1591753212, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.5e-05, 
    connect = 2.7e-05, pretransfer = 7.5e-05, starttransfer = 0.479948, 
    total = 0.47997)), class = "response")
