structure(list(url = "https://hillcrestgeo.ca/collections/fwa_stream_networks_sp?gnis_name=Sangan%20River", 
    status_code = 404L, headers = structure(list(server = "nginx/1.10.3 (Ubuntu)", 
        date = "Mon, 31 Aug 2020 19:18:02 GMT", `content-type` = "text/html", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.10.3 (Ubuntu)", 
            date = "Mon, 31 Aug 2020 19:18:02 GMT", `content-type` = "text/html; charset=utf-8", 
            `content-length` = "98", connection = "keep-alive", 
            `content-encoding` = "deflate", location = "/collections/fwa_stream_networks_sp?gnis_name=Sangan%20River", 
            vary = "Accept-Encoding", `x-frame-options` = "DENY", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list"))), list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.10.3 (Ubuntu)", 
            date = "Mon, 31 Aug 2020 19:18:02 GMT", `content-type` = "text/html", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"), 
    date = structure(1598901482, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.078082, namelookup = 3.7e-05, 
    connect = 3.9e-05, pretransfer = 9.7e-05, starttransfer = 0.07546, 
    total = 0.153586)), class = "response")
